name: My First Workflow

#The action that our workflow will do.
on: push 

#Jobs to describe the actions to take
jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: Welcome message
              run: echo "This is the first job"

            - name: List files
              run: ls

            - name: Read the files
              run: cat README.md