name: My First Workflow

#The action that our workflow will do.
on: push 

#Jobs to describe the actions to take
jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout Repo #Use the checkout action
              uses: actions/checkout@v4

            - name: List and read files
              run: |
                echo "This is the first job"
                ls -ltra
                cat README.md
                sudo apt-get install cowsay -y

            - name: Generate ASCII Artwork #Usage of third-party library
              run: cowsay -f dragon "Run... to... the... hills" >> dragon.txt