name: Matrix Configuration

on:
    push

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-24.04, windows-latest]
                images: [hello-world, alpine]
                exclude: #This field will exclude the specification
                  - images: alpine
                    os: windows-latest
                include:
                  - images: amd64/alpine
                    os: ubuntu-24.04
        runs-on: ${{matrix.os}}
        steps: 
        - name: Echo Docker Files
          run: docker info
        
        - name: Run image on ${{matrix.os}}
          run: docker run ${{matrix.images}} 