name: Run Multiple Jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Library
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run... to... the... hills" >> dragon.txt
        
        - name: Upload dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt

    test_job_2:
        needs: build_job_1 #Sentence to define the neccessary to run
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-file

        - name: Test File Exists
          run: ls

    deploy_job_3:
        needs: [build_job_1, test_job_2] #Sentence to define the neccessary to run
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-file

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying......
##testhsadfkjlhaslfjhsaljdfhl
#It's expected that when you run a workflow with multiple jobs, 
#all the jobs run at the same time, it's expected that some jobs
#turns in "fail" status. In this case Add "needs" condition