name: Exploring Variables and Secrets

on:
    push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker build ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password-${{ secrets.DOCKER.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Run
      run: docker run -d -p 8080:80 ${{ vars.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

################ workflow with variables ###############
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        env:
            CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
            DOCKER_USERNAME: bryan
            IMAGE_NAME: github-actions-nginx
        run: echo docker build-t $CONTAINER_REGISTRY/$DOCKER_USERNAMEe/$IMAGE_NAME:latest

      - name: Docker Login
        env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
            DOCKER_USERNAME: bryan
        run: echo docker login --username=$DOCKER_USERNAME --password-$DOCKER_PASSWORD

      - name: Docker Publish
        env:
            CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
            DOCKER_USERNAME: bryan
            IMAGE_NAME: github-actions-nginx
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Run
      env:
        CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
        DOCKER_USERNAME: bryan
        IMAGE_NAME: github-actions-nginx
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/DOCKER_USERNAME/IMAGE_NAME:latest

############## workflow with variables at job level #############
jobs:
  docker:
    env:
        CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
        DOCKER_USERNAME: bryan
        IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker build-t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env:
            DOCKER_PASSWORD: s3cUrePaSsw0rd
        run: docker login --username=$DOCKER_USERNAME --password-$DOCKER_PASSWORD

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
  deploy:
    env:
        CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
        DOCKER_USERNAME: bryan
        IMAGE_NAME: github-actions-nginx
    needs: docker
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Run

      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


